### ISSUE TITLE
Finishing setup directs user to incorrect link.

### ISSUE THREAD

**Issue by schaeken** [jtgrenz/Bootstrapify#6]
Replace `https://authme.shopify.com` with `https://authme.shopify.io`

![https://screenshot.click/15-31-edxbe-9pl5b.png](https://screenshot.click/15-31-edxbe-9pl5b.png)

**Comment by jtgrenz** [comment]
fixed https://github.com/jtgrenz/Bootstrapify/blob/master/bootstrapify.rb#L12
